theme: jekyll-theme-minimal
title: SplashGo!
description: Aplikasi SplashGo! adalah sistem digital untuk mengelola reservasi, data wisatawan, dan operasional destinasi laut secara efisien dan terintegrasi.
baseurl: /SplashGo